feat: add workflow templates
omec-project/.github pull request #1
Opened 2024-12-20 11:43 UTC by gatici

Adding each job templates can we used in any repository by providing input variables.

2024-12-20 11:44 UTC, gatici commented
This is still in-progress.

2024-12-20 14:39 UTC, ghislainbourgeois requested changes
Looks good, I have some comments

2024-12-20 14:39 UTC, ghislainbourgeois commented on workflows/create-release.yml
> +            echo "Version change not for release"
Maybe we want to exit or return right away here to bypass the rest of the code.
```suggestion
          else
            echo "Version change not for release"
            exit 0
```

2024-12-20 14:39 UTC, ghislainbourgeois commented on workflows/create-release.yml
> +          echo "version=$version"
I think we need to validate the content of VERSION before doing anything with it. Here, a bad actor could propose a PR where the VERSION file contains something like "v1.5.0 ; echo $GITHUB_TOKEN" and extract sensitive information.

While this example would probably be easy to spot, there have been some high profiles attack on open-source projects this year and I think we need to be a bit more cautious here.

This same comment would be valid everywhere we use content from the VERSION file.

2024-12-20 14:39 UTC, ghislainbourgeois commented on workflows/e2e-test.yml
> +          password: "dckr_pat_Up1vh3lGEKIfGDJuEj7Qb7OfdEE"
Shouldn't this be a secret?

This particular password should also be changed and not put as is in a secret.

2024-12-20 14:39 UTC, ghislainbourgeois commented on workflows/e2e-test.yml
> +          curl -u omectesting:dckr_pat_Up1vh3lGEKIfGDJuEj7Qb7OfdEE -X "DELETE" https://hub.docker.com/v2/repositories/${DOCKER_REPOSITORY}/5gc-amf/tags/${{ env.DOCKER_TAG }}/
Same comment regarding the password

2025-01-10 17:31 UTC, gab-arrobo requested changes

2025-01-10 17:31 UTC, gab-arrobo commented on workflows/branch-release.yml
> +          sha: '${{ github.event.pull_request.head.sha }}'
Please add EOL in all files. Thanks!

2025-01-10 17:31 UTC, gab-arrobo commented on workflows/update-version.yml
> +          version=${{ input.release-version }}
```suggestion
          version=${{ inputs.release-version }}
```

2025-01-10 17:31 UTC, gab-arrobo commented on workflows/update-version.yml
> +    if: ${{ input.release-changed == 'true' }}
Given that you are defining this variable as `boolean`, do you need to indicate `true` as a string?
```suggestion
    if: ${{ inputs.release-changed == 'true' }}
    runs-on: ubuntu-latest
```

2025-03-13 11:58 UTC, gatici commented on workflows/create-release.yml
> +          echo "version=$version"
e3e-test.yml is removed. This will be added in a different PR.

2025-03-13 11:59 UTC, gatici commented on workflows/e2e-test.yml
> +          curl -u omectesting:dckr_pat_Up1vh3lGEKIfGDJuEj7Qb7OfdEE -X "DELETE" https://hub.docker.com/v2/repositories/${DOCKER_REPOSITORY}/5gc-amf/tags/${{ env.DOCKER_TAG }}/
e3e-test.yml is removed. This will be added in a different PR.

2025-03-13 11:59 UTC, gatici commented on workflows/branch-release.yml
> +          sha: '${{ github.event.pull_request.head.sha }}'
Done

2025-03-13 21:33 UTC, gatici commented on workflows/update-version.yml
> +          version=${{ input.release-version }}
Done

2025-03-13 21:35 UTC, gatici commented on workflows/update-version.yml
> +    if: ${{ input.release-changed == 'true' }}
No. Fixed.

2025-03-13 21:46 UTC, gab-arrobo commented on workflows/branch-release.yml
> +          sha: '${{ github.event.pull_request.head.sha }}'
Some files still need the EOL. Below is one example
![image](https://github.com/user-attachments/assets/3b2f9426-5881-4ef6-a69f-0b43852df21e)

2025-03-13 22:44 UTC, gab-arrobo reviewed
Overall, it looks good to me.
Just in case do you have an example of how you are planning to use these GHAs in the different repositories? I am asking this because I was expecting to see something like this
```diff
      branch-name:
-        description: Name of the branch to checkout
-        required: false
-        type: string
-        default: ${{ github.ref }}
+        - ${{ input_branch }}
```
Also, my understanding was that the workflow call is done from the perspective of the "calling" repository (e.g., amf, smf, config5g, etc.). That is, do we need to pass the branch name that we need to take action on?

2025-03-13 22:44 UTC, gab-arrobo commented on workflows/hadolint.yml
> +
`git` is complaining about this extra line when I apply the patch
```suggestion
```
![image](https://github.com/user-attachments/assets/a1fef008-eeaf-45d7-84fa-b136423544dd)

2025-03-13 22:44 UTC, gab-arrobo commented on workflows/unit-test.yml
> +
`git` is complaining about this extra line when I apply the patch
```suggestion
```
![image](https://github.com/user-attachments/assets/a1fef008-eeaf-45d7-84fa-b136423544dd)

2025-03-13 22:44 UTC, gab-arrobo commented on workflows/hadolint.yml
> +
```suggestion
```

2025-03-13 22:44 UTC, gab-arrobo commented on workflows/license-check.yml
> +jobs:
```suggestion

jobs:
```

2025-03-13 22:44 UTC, gab-arrobo commented on workflows/lint.yml
> +        uses: golangci/golangci-lint-action@v6.1.1
```suggestion
        uses: golangci/golangci-lint-action@v6.5.1
```

2025-03-13 23:31 UTC, eb-oss requested changes

2025-03-13 23:31 UTC, eb-oss commented on workflows/fossa-scan.yml
> +          fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28
Should this be a secret?

2025-03-13 23:31 UTC, eb-oss commented on workflows/push-images.yml
> +      REGISTRY: registry.aetherproject.org
If these are meant to be reusable, I think all of these env vars should be inputs. These would be fine as default values, but it will be significantly more flexible if they can be set by the calling workflow.

2025-03-13 23:31 UTC, eb-oss commented on workflows/tag-github.yml
> +        run: |
This can be done quite easily with the `gh` app, and is more easily reusable if it's taken out into its own action. You can see the action I created in onos-project here: https://github.com/onosproject/.github/blob/ada32f9a5166ac244a4d564b80ea81ed5518e944/.github/actions/create-github-release-action/action.yml

However, that's not a change that HAS to happen now, but it's definitely an improvement I'd suggest making at some point.

2025-03-13 23:36 UTC, gab-arrobo commented on workflows/fossa-scan.yml
> +          fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28
No, this cannot be a secret because secrets are not shared as part of PRs. The `fossa-api-key` is a push-only token as suggested in the GHA: https://github.com/marketplace/actions/fossa-action#push-only-api-token

2025-03-14 00:05 UTC, eb-oss commented on workflows/fossa-scan.yml
> +          fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28
Ok, thanks for the confirmation.

2025-03-17 17:45 UTC, gab-arrobo requested changes

2025-03-17 17:45 UTC, gab-arrobo commented on workflows/release-image.yml
> +      - uses: docker/login-action@v3.3.0
```suggestion
      - uses: docker/login-action@v3.4.0
```

2025-03-18 08:52 UTC, gatici commented on workflows/unit-test.yml
> +
Removed.

2025-03-18 08:53 UTC, gatici commented on workflows/license-check.yml
> +jobs:
Added a line.

2025-03-18 08:53 UTC, gatici commented on workflows/lint.yml
> +        uses: golangci/golangci-lint-action@v6.1.1
Updated.

2025-03-18 09:51 UTC, gatici commented on workflows/tag-github.yml
> +        run: |
Done.

2025-03-18 09:51 UTC, gatici commented on workflows/release-image.yml
> +      - uses: docker/login-action@v3.3.0
Done

2025-03-19 03:58 UTC, gab-arrobo reviewed
Overall, it looks very good. I added some comments for your review. Thanks!

2025-03-19 03:58 UTC, gab-arrobo commented on .github/actions/create-github-release/action.yml
> +        fi
Add end of line
```suggestion
        fi

```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/tag-github.yml
> +          VERSION: ${{ steps.version-change.outputs.version }}
Add end of line
```suggestion
          VERSION: ${{ steps.version-change.outputs.version }}

```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/update-version.yml
> +          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
I think we can remove this line because it just indicates the user who approved the "previous" PR
```suggestion
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/update-version.yml
> +          git add VERSION && git commit -m "Update VERSION file to $NEW_VERSION" && git push
Why do you need these lines? The next task is taking care of that (add, commit and push)
```suggestion
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/update-version.yml
> +    workflows: ["Tag GitHub"]
Does this have to use brackets or can it be a list such as below?
```suggestion
    workflows:
        - "Tag GitHub"
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/tag-github.yml
> +          fetch-depth: 0
Why do you need to fetch all tags and branches?

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/tag-github.yml
> +        uses: ./actions/create-github-release
Is this the correct path? have you tested it?

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/unit-test.yml
> +          cache: true
I see we have two different `go`-related actions (`actions/setup-go@v5` and `WillAbides/setup-go-faster@v1.14.0`). I think we should rely in a single Go action for all of our GHAs, what do you think?

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/static-analysis.yml
> +        uses: actions/checkout@v4
```suggestion
      - uses: actions/checkout@v4
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/static-analysis.yml
> +      - name: Setup
```suggestion
      - name: Setup Go
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/stale-issue.yml
> +          stale-pr-message: 'This pull request has been stale for 120 days and will be closed in 15 days. Comment to keep it open.'
Should not the text for the number of days ("120" and "15") be changed based on the workflow input?
```suggestion
          stale-issue-message: 'This issue has been stale for ${{ inputs.days_before_stale }} days and will be closed in ${{ inputs.days_before_close}} days. Comment to keep it open.'
          stale-pr-message: 'This pull request has been stale for ${{ inputs.days_before_stale }} days and will be closed in ${{ inputs.days_before_close}} days. Comment to keep it open.'
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/release-image.yml
> +      - uses: actions/setup-go@v5
```suggestion
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/release-image.yml
> +    workflows: ["Tag GitHub"]
What about something like this?
```suggestion
    workflows:
        - "Tag GitHub"
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/push-images.yml
> +          make docker-push
I think there was an agreement in one of the TST meeting about not needing to publish "non-release" images. If so, I think we can remove this file and push the release images to Docker Hub and the Aether registry
@omec-project/5gc-maintainers, do you remember what we agreed about the "non-release" images (e.g., 5gc-amf:main-latest and 5gc-amf:main-commitId)?

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/lint.yml
> +        uses: actions/checkout@v4
```suggestion
      - uses: actions/checkout@v4
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/lint.yml
> +          submodules: true
Why do you need to pull the submodules? I do not think any repo has a submodule
```suggestion
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/build.yml
> +        run: go mod download
Why do you need this step? We did not need it before

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/branch-release.yml
> +    workflows: ["Tag GitHub"]
What about something like this
```suggestion
    workflows:
        - "Tag GitHub"
```

2025-03-19 03:58 UTC, gab-arrobo commented on .github/workflows/branch-release.yml
> +          branch: "rel-${{ github.event.workflow_run.outputs.version_branch }}"
Just in case, have you checked what we can do regarding the creation of release branches (branch name is different than the content o version file)? For example, in the `amf` repo, branch `rel-1.3` has VERSION file with content `1.4.0`

2025-03-19 03:58 UTC, gab-arrobo commented on .github/actions/create-github-release/action.yml
> +        if gh release create "${{ inputs.VERSION }}" --generate-notes; then
Should I understand that the GitHub runners have, by default, the GitHub client (gh) installed? Additionally, I should understand that this cannot be in the same GHA (i.e., `tag-github`) and that is why it is in its own directory (actions), correct?

2025-03-19 04:15 UTC, gab-arrobo commented
@gatici,
BTW, I think we also need to add a Dependabot to handle dependency updates for the GitHub Action, correct?

2025-03-19 11:24 UTC, gatici commented on .github/actions/create-github-release/action.yml
> +        fi
Done.

2025-03-19 11:25 UTC, gatici commented on .github/workflows/tag-github.yml
> +          VERSION: ${{ steps.version-change.outputs.version }}
Done

2025-03-19 11:26 UTC, gatici commented on .github/workflows/update-version.yml
> +          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
Done

2025-03-19 11:30 UTC, gatici commented on .github/workflows/update-version.yml
> +          git add VERSION && git commit -m "Update VERSION file to $NEW_VERSION" && git push
Removed.

2025-03-19 11:58 UTC, gatici commented on .github/workflows/tag-github.yml
> +          fetch-depth: 0
Because create-release job creates releases notes including all relevant commits.

2025-03-19 12:00 UTC, gatici commented on .github/workflows/tag-github.yml
> +        uses: ./actions/create-github-release
./.github/actions/create-github-release is the correct path. Fixed.

2025-03-19 12:04 UTC, gatici commented on .github/workflows/unit-test.yml
> +          cache: true
OK. actions/setup-go@v5 is preferred.

2025-03-19 12:05 UTC, gatici commented on .github/workflows/static-analysis.yml
> +        uses: actions/checkout@v4
Done

2025-03-19 12:49 UTC, gatici commented on .github/workflows/static-analysis.yml
> +      - name: Setup
Done

2025-03-19 12:55 UTC, gatici commented on .github/workflows/stale-issue.yml
> +          stale-pr-message: 'This pull request has been stale for 120 days and will be closed in 15 days. Comment to keep it open.'
Good catch. Done.

2025-03-19 12:56 UTC, gatici commented on .github/workflows/release-image.yml
> +      - uses: actions/setup-go@v5
Done

2025-03-19 12:56 UTC, gatici commented on .github/workflows/release-image.yml
> +    workflows: ["Tag GitHub"]
Done

2025-03-19 13:02 UTC, gatici commented on .github/workflows/lint.yml
> +        uses: actions/checkout@v4
Done

2025-03-19 14:39 UTC, gatici commented on .github/workflows/lint.yml
> +          submodules: true
OK. Removed.

2025-03-19 14:43 UTC, gatici commented on .github/workflows/build.yml
> +        run: go mod download
It is used to avoid missing dependency issues during build. They may not happen but  just a  best practice for Go based automation workflows.

2025-03-19 14:43 UTC, gatici commented on .github/workflows/build.yml
> +        run: go mod download
Removed.

2025-03-19 14:43 UTC, gatici commented on .github/workflows/branch-release.yml
> +    workflows: ["Tag GitHub"]
Done

2025-03-19 15:14 UTC, gatici commented on .github/actions/create-github-release/action.yml
> +        if gh release create "${{ inputs.VERSION }}" --generate-notes; then
Yes, Github runners have the Github Client installed by default.
If we would like to use it a composite-action, which is a reusable action, it should be defined under actions.
But this is not the only way to define it.
The logic can be written directly into the workflow by not defining an action.

2025-03-19 15:22 UTC, gatici commented
> @gatici, BTW, I think we also need to add a Dependabot to handle dependency updates for the GitHub Action, correct?

Yes, I will add Dependabot.

2025-03-20 09:50 UTC, gatici commented on .github/workflows/push-images.yml
> +          make docker-push
Hello Gabriel,
According to notes of TSC meeting which is held on 1-7-25, it is decided not to publish per-PR images.

2025-03-20 09:54 UTC, gatici commented on .github/workflows/branch-release.yml
> +          branch: "rel-${{ github.event.workflow_run.outputs.version_branch }}"
Hello Gabriel,
We can enforce the compatibility for the new changes form now-on. 
For the old branches (incompatible branch name/VERSION),  we can take the branch name into account.

2025-03-20 10:34 UTC, gatici commented on .github/workflows/push-images.yml
> +          make docker-push
In the workflows of NF, I will trigger this workflow only a new tag is created.

2025-03-20 10:46 UTC, gatici commented on .github/workflows/branch-release.yml
> +          branch: "rel-${{ github.event.workflow_run.outputs.version_branch }}"
In tag-github job, I added a step to validate the compatibility between version and the branch.

2025-03-20 11:13 UTC, gatici commented
> o handle dependency updates for the GitHub Actio

Added a dependabot.yml to perform dependency updates.

2025-03-20 15:23 UTC, gab-arrobo reviewed
+1

2025-03-20 15:23 UTC, gab-arrobo commented on .github/dependabot.yml
> +    target-branch: "main"
Please add end of line
```suggestion
    target-branch: "main"

```

2025-03-20 15:23 UTC, gab-arrobo commented on .github/workflows/tag-github.yml
> +
`git apply` is complaining due to these blank spaces (tab)
```
$ git apply pr.patch
pr.patch:524: trailing whitespace.

pr.patch:527: trailing whitespace.

pr.patch:534: trailing whitespace.

warning: 3 lines add whitespace errors.
```

```suggestion

```

2025-03-20 15:25 UTC, gab-arrobo commented on .github/workflows/push-images.yml
> +          make docker-push
I think we need to modify the `push-images` GHA to not only pushing images to Docker Hub but also to the Aether registry. It seems to me that currently, this GHA (in this PR) only pushes the images to Docker Hub, correct?

2025-03-20 15:27 UTC, gab-arrobo commented
@thakurajayL @ghislainbourgeois @eb-oss,
I think this PR is almost ready to merge. Any further thoughts/comments about it?
Thanks!

2025-03-20 16:13 UTC, gatici commented on .github/dependabot.yml
> +    target-branch: "main"
Done.

2025-03-20 16:14 UTC, gatici commented on .github/workflows/tag-github.yml
> +
Removed.

2025-03-20 16:14 UTC, gatici commented on .github/workflows/tag-github.yml
> +
Removed.

2025-03-20 16:15 UTC, gatici commented on .github/dependabot.yml
> +      interval: "weekly"
Done

2025-03-20 16:25 UTC, gab-arrobo commented
@gatici, thanks for addressing my comments. One more thing, I think there is no need to have both `push-images` and `release-image`. I think we should only keep `release-image` and accordingly update the input parameters such that it can push that images to Docker Hub and Aether registry, but we need to keep in mind that the credentials for both (Docker Hub and Aether registry) are different.
Moreover, do we need to create both images from "scratch" by using `make docker-build` or should we create it once (and push it) and then (re)tag the image to push it to the other registry with its own credentials. What are your thoughts on this?

2025-03-20 16:40 UTC, gatici commented
> @gatici, thanks for addressing my comments. One more thing, I think there is no need to have both `push-images` and `release-image`. I think we should only keep `release-image` and accordingly update the input parameters such that it can push that images to Docker Hub and Aether registry, but we need to keep in mind that the credentials for both (Docker Hub and Aether registry) are different. Moreover, do we need to create both images from "scratch" by using `make docker-build` or should we create it once (and push it) and then (re)tag the image to push it to the other registry with its own credentials. What are your thoughts on this?

I support your opinion. We can reuse same image and just re-tag it and we can reduce push-images workflow.
Here, please help me to confirm the registry and repository details. 

aether
registry: "registry.aetherproject.org"
repository: sdcore

docker
registry: docker.io
repository: ?

2025-03-20 17:27 UTC, gatici commented
> > @gatici, thanks for addressing my comments. One more thing, I think there is no need to have both `push-images` and `release-image`. I think we should only keep `release-image` and accordingly update the input parameters such that it can push that images to Docker Hub and Aether registry, but we need to keep in mind that the credentials for both (Docker Hub and Aether registry) are different. Moreover, do we need to create both images from "scratch" by using `make docker-build` or should we create it once (and push it) and then (re)tag the image to push it to the other registry with its own credentials. What are your thoughts on this?
> 
> I support your opinion. We can reuse same image and just re-tag it and we can reduce push-images workflow. Here, please help me to confirm the registry and repository details.
> 
> aether registry: "registry.aetherproject.org" repository: sdcore
> 
> docker registry: docker.io repository: ?

This is addressed in the latest commit.

2025-03-20 17:47 UTC, gab-arrobo requested changes

2025-03-20 17:47 UTC, gab-arrobo commented on .github/workflows/release-image.yml
> +          make docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.workflow_run.outputs.version }}
```suggestion
      - name: Build and Push Docker image
        run: |
          make docker-build
          make docker-push
```

2025-03-20 17:56 UTC, gab-arrobo reviewed
Please ping me through Slack

2025-03-20 17:56 UTC, gab-arrobo commented on .github/workflows/release-image.yml
> +      AETHER_IMAGE_NAME: ${{ inputs.aether_repository_namespace}}/${{ inputs.repository_name }}
How are you using these two variables?

2025-03-20 18:31 UTC, gatici commented on .github/workflows/release-image.yml
> +          make docker push ${{ env.DOCKER_IMAGE_NAME }}:${{ github.event.workflow_run.outputs.version }}
This is fixed.

2025-03-20 18:32 UTC, gatici commented on .github/workflows/release-image.yml
> +      AETHER_IMAGE_NAME: ${{ inputs.aether_repository_namespace}}/${{ inputs.repository_name }}
Removed.

2025-03-20 18:35 UTC, gab-arrobo approved these changes
+1

2025-03-20 18:38 UTC, gab-arrobo commented
@ghislainbourgeois, @eb-oss,
I am good with the current version of this PR. I need your help reviewing it and approving it before this can be merged (this is because you requested changes that I think have been already addressed).
Thanks!

2025-03-20 19:13 UTC, eb-oss approved these changes
LGTM

2025-03-20 19:47 UTC, merged